// AUTO-GENERATED by scripts/generate-mdrag-types.mjs — DO NOT EDIT.
// Source: mdrag OpenAPI, pruned to /api/v1/primitives/*. Regenerate with:
//   MDRAG_OPENAPI_URL=http://localhost:8017/openapi.json npm run generate:mdrag-types

export interface paths {
    "/api/v1/primitives/plan-research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Research
         * @description Decompose a topic into sub-questions + comparison axes via the real
         *     ``RefineStage`` — synchronous, stateless, no job_id/persistence/polling.
         */
        post: operations["plan_research_api_v1_primitives_plan_research_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/primitives/synthesize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synthesize
         * @description Synthesize caller-supplied, pre-vetted findings into a narrative via
         *     the real ``SynthesisStage`` — synchronous, stateless.
         *
         *     Every supplied finding is marked ``supported`` when building the
         *     throwaway context (see module docstring) — there is no verify stage
         *     here.
         */
        post: operations["synthesize_api_v1_primitives_synthesize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/primitives/extract-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Results
         * @description Schema-constrained extraction with mandatory per-value grounding.
         *
         *     Not backed by an existing Stage class (no stage does generic
         *     schema-driven extraction) — this is a new thin wrapper directly over
         *     ``LlmPort.complete(schema=...)``, the same structured-output mechanism
         *     every existing stage already uses.
         *
         *     Every extracted leaf value MUST carry a verbatim quote + character span
         *     into ``source_text``. Those quotes/spans are checked deterministically
         *     (pure Python, no model call — see
         *     ``mdrag.interfaces.api.routers.primitives.grounding.validate_grounding``)
         *     before this ever returns: a caller never sees a fabricated quote, and a
         *     validation failure raises a 422 rather than silently returning
         *     unvalidated or partial output (issue #886 comment, points 1 and 3).
         *
         *     Uses ``ModelRole.FAST`` deliberately — NOT a reasoning model (point 4):
         *     the schema already pins the output shape, so reasoning tokens add
         *     latency without adding precision here.
         */
        post: operations["extract_results_api_v1_primitives_extract_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/primitives/search-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Providers
         * @description Search one Provider and (by default) hydrate every hit — synchronous,
         *     stateless, LLM-free. See the module docstring's "search-providers"
         *     section for the hydration-folding and auth-bounding decisions.
         *
         *     Bounded by ``body.available_providers`` (ADR 0023's existing stand-in for
         *     real per-user Provider auth, reused verbatim): a request for a Provider
         *     not in that caller-declared list is rejected with 403 before any
         *     resolution is attempted — never an unbounded fallback.
         */
        post: operations["search_providers_api_v1_primitives_search_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/primitives/critique": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Critique Endpoint
         * @description Adversarially review every subject against every criterion — the
         *     domain-agnostic generalization of ``VerifyStage`` (issue #900, ADR-0026).
         *
         *     One batched ``ModelRole.THINKING`` call judges each ``body.subjects``
         *     entry against each ``body.criteria`` string; a subject or criterion the
         *     model's structured output omits defaults to failed, never silently
         *     promoted (see ``critique.reconcile_subject``). Judges only — never
         *     rewrites: a caller wanting a replacement for a failed subject should call
         *     ``POST /api/v1/primitives/synthesize`` instead.
         */
        post: operations["critique_endpoint_api_v1_primitives_critique_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CriterionVerdict
         * @description One criterion's reconciled pass/fail for one subject.
         */
        CriterionVerdict: {
            /** Criterion */
            criterion: string;
            /**
             * Passed
             * @description Never silently promoted: a criterion the model's structured output omitted for this subject defaults to False, not True.
             * @default false
             */
            passed: boolean;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /**
         * CritiqueRequest
         * @description POST /api/v1/primitives/critique request body (issue #900, ADR-0026).
         *
         *     Generalizes ``VerifyStage`` (an adversarial skeptic hardcoded to ONE
         *     implicit criterion — "supported by cited evidence" — over research
         *     findings) into a domain-agnostic "assertion + criteria -> pass/fail +
         *     reasoning" contract any caller can use, e.g. Pattern Hunter's Red Team
         *     node judging a recommendation against named operator fears instead of
         *     retrieved evidence.
         */
        CritiqueRequest: {
            /**
             * Context
             * @description Shared background all subjects are judged against — VerifyStage's ctx.topic maps here; Pattern Hunter would put e.g. 'small business, cash-strapped, fears asset loss/legal exposure' here.
             * @default
             */
            context: string;
            /**
             * Criteria
             * @description Named pass/fail criteria — the actual generalization over VerifyStage, which had exactly one hardcoded criterion. A VerifyStage-shaped caller supplies criteria=['supported by cited evidence']; Pattern Hunter supplies its own list, e.g. ['actionable within 48h', 'costs under $200', 'addresses a fear not just an opportunity', 'has a natural opening line']. EVERY subject is judged against EVERY criterion in one batched call.
             */
            criteria: string[];
            /**
             * Subjects
             * @description The things to adversarially review, batched into one call
             */
            subjects: components["schemas"]["CritiqueSubject"][];
            /**
             * Instructions
             * @description Optional extra framing, mirrors ExtractResultsRequest.instructions
             */
            instructions?: string | null;
        };
        /**
         * CritiqueResponse
         * @description POST /api/v1/primitives/critique response body.
         *
         *     Replacement-generation is explicitly OUT of scope (ADR-0026): a caller
         *     whose subject fails and wants a replacement should make a follow-up call
         *     to ``POST /api/v1/primitives/synthesize`` — critique only judges, it never
         *     rewrites.
         */
        CritiqueResponse: {
            /** Verdicts */
            verdicts?: components["schemas"]["CritiqueVerdict"][];
            /**
             * Overall Passed
             * @description True iff every subject's `passed` is True
             */
            overall_passed: boolean;
        };
        /**
         * CritiqueSubject
         * @description One thing being adversarially reviewed.
         *
         *     Generalizes ``VerifyStage``'s per-claim ``(claim, source_refs)`` pair
         *     (``mdrag.capabilities.research.staged.stages``) — see ADR-0026.
         */
        CritiqueSubject: {
            /**
             * Id
             * @description Caller-assigned identifier, echoed back on the matching CritiqueVerdict.subject_id — unambiguous even when two subjects happen to share the same assertion text.
             */
            id: string;
            /**
             * Assertion
             * @description The claim / recommendation / whatever is under review
             */
            assertion: string;
            /**
             * Evidence
             * @description Optional supporting refs/quotes/urls specific to THIS subject — generalizes VerifyStage's per-claim source_refs. May legitimately be empty when criteria aren't evidence-based (e.g. Pattern Hunter's fear-based criteria: 'addresses a fear not just an opportunity' has no source to cite).
             */
            evidence?: string[];
        };
        /**
         * CritiqueVerdict
         * @description One subject's adversarial review outcome.
         *
         *     ``passed``/``verdict`` mirror the two-tier pattern
         *     ``ExtractResultsResponse`` already established
         *     (``answer_found``/``complete_answer_found`` as canonical booleans plus
         *     richer fields alongside): ``passed`` is the ONE machine-actionable gate,
         *     ``verdict`` is a caller-vocabulary display label. Skepticism-by-default
         *     applies throughout — a subject the model's structured output omits
         *     entirely gets ``passed=False``, ``verdict="unverifiable"``, and every
         *     criterion marked failed, never silently promoted (see
         *     ``mdrag.capabilities.research.staged.critique.reconcile_subject``).
         */
        CritiqueVerdict: {
            /**
             * Subject Id
             * @description Echoes CritiqueSubject.id verbatim
             */
            subject_id: string;
            /**
             * Passed
             * @description The canonical, machine-actionable gate: AND across every one of this subject's criteria. Computed server-side, never trusted from a model's own top-level claim.
             */
            passed: boolean;
            /**
             * Verdict
             * @description Free-text domain label the CALLER's vocabulary flows through untouched — 'supported'/'refuted'/'unverifiable' for a VerifyStage-shaped caller, 'pass'/'cut' for a Pattern-Hunter-shaped caller. Not a fixed enum: whatever the model returned for this subject, or 'unverifiable' when the model omitted the subject entirely.
             * @default unverifiable
             */
            verdict: string;
            /**
             * Criteria
             * @description Per-criterion breakdown, in the request's criteria order
             */
            criteria?: components["schemas"]["CriterionVerdict"][];
            /**
             * Rationale
             * @description Overall rationale; skepticism-by-default applies here too
             * @default
             */
            rationale: string;
        };
        /**
         * ExtractResultsRequest
         * @description POST /api/v1/primitives/extract-results request body.
         *
         *     Amended contract (issue #886 comment) — mandatory per-value grounding,
         *     not a bare "text + schema -> JSON" call. See
         *     ``mdrag.interfaces.api.routers.primitives.grounding`` for the
         *     schema-conversion + deterministic verbatim-quote validation this powers.
         */
        ExtractResultsRequest: {
            /**
             * Source Text
             * @description The prose to extract from
             */
            source_text: string;
            /**
             * Json Schema
             * @description JSON Schema (supported subset: object/array/string/integer/number/boolean/enum, nested arbitrarily) describing ONE schema's worth of fields to extract, top-level type 'object'. An optional 'required': [name, ...] array at any object level is honored by the RESPONSE contract (see ExtractResultsResponse.missing_required_fields) — a caller-required field that comes back null forces answer_found=false rather than a silent half-populated success. Split a large compound schema into several calls — one sub-schema per call — rather than one giant compound schema: a smaller model silently fabricates intermediate fields in compound schemas (issue #886 comment, point 5).
             */
            json_schema: {
                [key: string]: unknown;
            };
            /**
             * Instructions
             * @description Optional extra guidance/persona/domain framing for the extraction
             */
            instructions?: string | null;
        };
        /**
         * ExtractResultsResponse
         * @description Grounded extraction result.
         *
         *     ``result`` mirrors the caller's ``json_schema`` shape, except every leaf
         *     scalar is replaced by ``{"value", "quote", "start", "end"}`` (or ``null``
         *     when genuinely not found) — grounding is mandatory, never optional, and
         *     every quote/span pair has already been deterministically verified against
         *     ``source_text`` (pure Python, no model call) before this response is
         *     returned; a validation failure raises instead of returning unvalidated
         *     data (see ``router.py``).
         *
         *     ``missing_required_fields`` is the RESPONSE-CONTRACT enforcement of the
         *     caller's ``json_schema`` ``required`` list (distinct from the LLM-facing
         *     schema, which stays fully nullable so the model always has an honest way
         *     to say "not present" — see ``grounding.py``'s module docstring for the
         *     two-layer rationale). When non-empty, this is the "refuse" route:
         *     ``answer_found`` is forced ``False`` and ``result`` still carries
         *     whatever WAS grounded — a 200 response representing a well-formed,
         *     deliberate outcome (not found), never a 500.
         */
        ExtractResultsResponse: {
            /**
             * Answer Found
             * @description True iff at least one requested field was genuinely grounded in source_text AND no caller-required field came back null. Forced False whenever missing_required_fields is non-empty, regardless of what the model itself reported.
             */
            answer_found: boolean;
            /**
             * Complete Answer Found
             * @description True iff every requested field was found and grounded. For open-web/unbounded research this is a judgment call, not a deterministic structural check (issue #886 comment, point 2 caveat) — it is NOT independently re-verified server-side, except that it is forced False whenever missing_required_fields is non-empty (a caller-required field missing is definitionally incomplete).
             */
            complete_answer_found: boolean;
            /**
             * Result
             * @description The extracted, grounded values — shape follows the caller's json_schema
             */
            result: {
                [key: string]: unknown;
            };
            /**
             * Missing Required Fields
             * @description Dotted/bracketed paths (relative to 'result') of caller-'required' fields whose extracted value came back null. Empty for every field the caller didn't mark required, and empty when every required field was grounded — non-empty is the explicit, machine-readable 'refuse' signal.
             */
            missing_required_fields?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PlanResearchRequest
         * @description POST /api/v1/primitives/plan-research request body.
         *
         *     Just a topic — no job_id, no persistence, no polling (issue #886, user
         *     story 8).
         */
        PlanResearchRequest: {
            /**
             * Topic
             * @description Research topic to decompose
             */
            topic: string;
        };
        /**
         * PlanResearchResponse
         * @description Only the RefineStage output fields relevant to an external caller.
         *
         *     No job_id, no turning_points, no completed_stages — those are internal
         *     to the durable ``ResearchContext`` and have no meaning for a stateless
         *     single call.
         */
        PlanResearchResponse: {
            /** Subquestions */
            subquestions?: string[];
            /** Comparison Axes */
            comparison_axes?: string[];
            /**
             * Resolved Entity
             * @description RefineStage's disambiguated entity — a direct read of ResearchContext.resolved_entity, which falls back to the raw topic when refine found no ambiguity to resolve.
             * @default
             */
            resolved_entity: string;
        };
        /**
         * SearchProvidersRequest
         * @description POST /api/v1/primitives/search-providers request body (issue #899).
         *
         *     Mirrors ``mdrag.providers.models.ProviderSearchQuery`` field-for-field
         *     (same four universal filters + ``extra`` escape hatch, same defaults) so
         *     this endpoint is a genuinely thin wrapper — no new query vocabulary
         *     invented for HTTP callers.
         */
        SearchProvidersRequest: {
            /**
             * Provider
             * @description Provider name to search, e.g. 'gdrive'/'slack'/'web'/'youtube'/'letta' (mdrag.providers.entrypoint.PROVIDER_REGISTRY). Must also appear in `available_providers` — see that field.
             * @default drive
             */
            provider: string;
            /**
             * Available Providers
             * @description The caller's authenticated Provider set — the SAME field/semantics as ResearchRequest.available_providers (ADR 0023): an explicit, caller-declared stand-in for real per-user Provider-auth resolution, which does not exist in this codebase yet (see router module docstring, 'Auth-bounding' section). `provider` MUST be a member of this list or the request is rejected (403) — absent/empty rejects every provider (deny-by-default). This endpoint never falls back to an unbounded 'search everything'.
             */
            available_providers?: string[];
            /**
             * Text
             * @description Free-text keyword query
             */
            text: string;
            /**
             * Created After
             * @description Lower bound on the source-side timestamp
             */
            created_after?: string | null;
            /**
             * Created Before
             * @description Upper bound on the source-side timestamp
             */
            created_before?: string | null;
            /**
             * Author
             * @description Restrict to content authored/owned by this identity
             */
            author?: string | null;
            /**
             * Limit
             * @description Maximum number of results to return
             * @default 10
             */
            limit: number;
            /**
             * Extra
             * @description Provider-specific passthrough, e.g. {'locator': '#channel'} for slack (as a folder/channel hint) or {'agent_ids': [...]} for letta — mirrors ProviderSearchQuery.extra exactly.
             */
            extra?: {
                [key: string]: unknown;
            };
            /**
             * Hydrate
             * @description Default-hydrate (True) per the Provider system's own stated default (mdrag.providers.hydration.hydrate_envelope: 'Default behavior with no gate: hydrate every result'). Set False to get lightweight results only (title/url/snippet, no deep-fetch) — e.g. for a caller doing its own relevance filtering before deciding what to fetch.
             * @default true
             */
            hydrate: boolean;
        };
        /**
         * SearchProvidersResponse
         * @description Grounded-in-the-real-thing response: the echoed query plus results.
         *
         *     ``results`` is ``list[dict]`` rather than ``list[ProviderResult]`` on
         *     purpose: each result is dumped via its OWN concrete subclass's
         *     ``model_dump()`` (``GDocResult``/``SlackResult``/``SearxngResult``/
         *     ``YouTubeResult``/``LettaResult``), so Provider-specific fields
         *     (``file_id``, ``channel_id``, ``video_id``, ``agent_id``, ...) survive.
         *     Declaring the field as the shared base ``ProviderResult`` type would
         *     silently truncate every result down to the base class's common fields
         *     during FastAPI/pydantic response serialization (verified: pydantic v2
         *     serializes a field by its DECLARED type, not the runtime subclass,
         *     unless the field is wrapped in ``SerializeAsAny``) — a real, easy-to-miss
         *     footgun for a heterogeneous Provider-result envelope like this one.
         */
        SearchProvidersResponse: {
            /** Provider */
            provider: string;
            /**
             * Results
             * @description Each item is one ProviderResult subclass's own model_dump(mode='json')
             */
            results?: {
                [key: string]: unknown;
            }[];
            /**
             * Hydrated
             * @description True iff hydration was requested (hydrate=True) AND completed without error
             */
            hydrated: boolean;
            /**
             * Hydration Error
             * @description Set iff hydrate=True was requested but hydrate_envelope() raised partway through — results may be a mix of hydrated and still-lightweight items (same partial-progress semantics as hydrate_envelope itself; see its docstring). Never silently swallowed — always surfaced here, per this repo's no-silent-failures rule.
             */
            hydration_error?: string | null;
        };
        /**
         * SynthesisFinding
         * @description One caller-supplied, already-vetted finding/piece of evidence.
         *
         *     Marked ``supported`` unconditionally when this endpoint builds its
         *     throwaway ``ResearchContext`` (issue #886 amendment): SynthesisStage only
         *     ever consumes ``supported``-verdict claims (normally VerifyStage's
         *     output), and this standalone endpoint has no verify step. Callers are
         *     expected to have already done their own vetting (e.g. a red-team pass)
         *     before calling this endpoint.
         */
        SynthesisFinding: {
            /** Claim */
            claim: string;
            /**
             * Source Url
             * @description Optional citation for this claim
             * @default
             */
            source_url: string;
        };
        /**
         * SynthesizeRequest
         * @description POST /api/v1/primitives/synthesize request body.
         */
        SynthesizeRequest: {
            /** Topic */
            topic: string;
            /**
             * Findings
             * @description Caller's own pre-vetted findings/evidence to synthesize
             */
            findings: components["schemas"]["SynthesisFinding"][];
            /**
             * Comparison Axes
             * @description Optional comparison axes; SynthesisStage infers a single synthesized entity per axis when the topic isn't a head-to-head comparison
             */
            comparison_axes?: string[];
        };
        /**
         * SynthesizeResponse
         * @description Only the SynthesisStage narrative — no comparison_frame/turning_points.
         */
        SynthesizeResponse: {
            /**
             * Synthesis
             * @default
             */
            synthesis: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    plan_research_api_v1_primitives_plan_research_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanResearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    synthesize_api_v1_primitives_synthesize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SynthesizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SynthesizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_results_api_v1_primitives_extract_results_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractResultsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_providers_api_v1_primitives_search_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchProvidersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchProvidersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    critique_endpoint_api_v1_primitives_critique_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CritiqueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CritiqueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
